CREATE DATABASE IF NOT EXISTS pp_note; USE pp_note;

CREATE TABLE ESTADO ( 
ID_ESTADO INT PRIMARY KEY, 
DESCRIPCION VARCHAR(100) NOT NULL );

CREATE TABLE COMPUTADORA ( 
NUMERO_DE_SERIE INT PRIMARY KEY, 
NOMBRE VARCHAR(50), 
MARCA VARCHAR(50), 
MODELO VARCHAR(50), 
ID_ESTADO INT, 
FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO) 
);

CREATE TABLE usuario ( 
id INT PRIMARY KEY, 
nombre varchar(255), 
email VARCHAR(100), 
contraseña VARCHAR(100), 
division VARCHAR(100), 
especialidad VARCHAR(100), 
tipo_usuario VARCHAR(100), 
fecha date );

CREATE TABLE PRESTAMO ( 
ID_PRESTAMO INT PRIMARY KEY, 
FECHA_PRESTAMO DATE, 
HORA_INICIO_PRESTAMO TIME, 
HORA_FIN_PRESTAMO TIME, 
ESTADO_PRESTAMO VARCHAR(50), 
ID_USUARIO INT, FOREIGN KEY (ID_USUARIO) REFERENCES usuario(id) 
);

CREATE TABLE HISTORIAL_PRESTAMO ( 
ID_HISTORIAL INT PRIMARY KEY, 
ID_PRESTAMO INT, DESCRIPCION VARCHAR(255), 
FOREIGN KEY (ID_PRESTAMO) REFERENCES PRESTAMO(ID_PRESTAMO) 
);

CREATE TABLE MANTENIMIENTO ( 
ID_MANTENIMIENTO INT PRIMARY KEY, 
DESCRIPCION VARCHAR(255), 
FECHA_MANTENIMIENTO DATE, 
ID_COMPUTADORA INT, 
FOREIGN KEY (ID_COMPUTADORA) REFERENCES COMPUTADORA(NUMERO_DE_SERIE) 
);                                                                                                                                                                 

ALTER TABLE usuario MODIFY COLUMN tipo_usuario ENUM('admin', 'profesor', 'alumno') DEFAULT 'alumno';
